version: '3'

services:
  sickrage:
    image: chewy85500/rpi-sickrage
    volumes: 
      - data:/data
      - /mnt/nfs:/mnt/nfs
    ports:
      - 8081:8081
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure

  couchpotato:
    image: chewy85500/rpi-couchpotato
    volumes: 
      - data:/data
      - /mnt/nfs:/mnt/nfs
    ports:
      - 5050:5050
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure

  nzbget:
    image: chewy85500/rpi-nzbget
    volumes: 
      - data:/data
    ports:
      - 6789:6789
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure

  transmission:
    image: chewy85500/rpi-transmission
    volumes: 
      - data:/data
      - transmission-etc:/etc/transmission-daemon
    ports:
      - 9091:9091
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure

volumes:
  data:
  transmission-etc:
