version: '3'

services:
  sickrage:
    image: chewy85500/rpi-sickrage
    volumes:
      - /storage/data:/data
      - sickrage-data:/opt/Sickrage
      - /mnt/nfs:/mnt/nfs
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1

  couchpotato:
    image: chewy85500/rpi-couchpotato
    volumes:
      - /storage/data:/data
      - /mnt/nfs:/mnt/nfs
    ports:
      - target: 5050
        published: 5050
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1

  nzbget:
    image: chewy85500/rpi-nzbget
    volumes:
      - /storage/data:/data
    ports:
      - target: 6789
        published: 6789
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1

  transmission:
    image: chewy85500/rpi-transmission
    volumes:
      - /storage/data:/data
      - transmission-etc:/etc/transmission-daemon
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1

volumes:
  transmission-etc:
  sickrage-data:
